// English Translations
const Map<String, String> enUS = {
  //other project
  'enter_mobile': 'Enter your mobile number',
  'sent_code': 'We will send you a confirmation code',
  'enter_phone_number': 'Enter the phone number.',
  'phone_invalid': "Phone number format error. The phone number must start with + and be 9-15 digits long.",
  'enter_sms_code': "Enter code sent \nto your number",
  'we_sent_sms': "We sent it to the number ",
  'receive_code': "I did`nt receive code. ",
  'resend_code': "Resend Code",
  'next': "Next",
  'password': "Password",
  'new_password': "New Password",
  'enter_new_password': "Enter new password",
  'confirm_password': "Confirm Password",
  'enter_confirm_password': "Please enter confirm password",
  'save': "Save",
  'msg_enter_password': "Enter the password number.",
  'msg_enter_confirm_password': "Please enter the same password!",
  'login': "Login",
  'username': "Username",
  'lang': "en_US",
  'internal_server_error': "System error! Please try again later!",
  'location': "Location",
  'clock_in': 'Clock In',
  'clock_out': 'Clock Out',
  'working_hr': "Workiving Hr's",
  'language': "Language",
  'log_out': "Log Out",
  'attendance': "Attendance",
  'date': "Date",
  'try_again': "Please try again!",
  'forget_pressed_button':
      "You didn't press the 'Clock Out' button yesterday, please report it to the HR supervisor!",
  'disable': "This button is only pressed when you come and go!",
  'check_network': "You are offline. Please, check your Internet connection!",
  'incorrectly_phone': "Please enter the number available in the system!",
  'invalid_password': "Please enter the password correctly!",

// current project
// page intro
  'intro_header_one': "More than 200 classes \n with promotions and bonuses",
  'intro_content_one': "Get gifts, discounts for you",
  'button_next': "Next",
  "button_enter": "Enter",

//language page
  "str_choose_lang": "Choose language",

//setting_detail_page
  "str_guests": "Visitors",
  "str_people_count": "Number of people",
  "str_choose_date": "Choose date",
  "str_choose_room": "Choose room",
  "str_choose_time": "Select the arrival time",
  "str_clear": "Clear",
  "str_next": "Next",
  "str_room": "Room",
  "str_price": "Price",

  ///detailPage
  "location_of_city": "Location",
  "region_locatin":"Amir tumer region",
  "city":"Tashkent",
  "Description":"Description",
  "description_detail":"The restaurant in the lovingly restored Sericulture pavilion at VDNKh has been operating since May 2016. The establishment has two halls, in the summer two large verandas are added to them; around the park, and very close to the Green Theater.",
  "working_mode":"Working mode",
  "working_hour":"Today 10:00 - 23:00",
  "more":"More",
  "information":"Information",
  "route":"Route",
  "call":"Call",
  "underline":"metro",
  "tv":"Tv",
  "parking":"parking",
  "verandas":"verandas",
  "wifi":"Wi-Fi",

  // Notification page
  "news":"News",
  "message":"Message",
  "vastok":"Vastok",
  "tashkent":"Tashkent",
  "yunusabad":"Yunusabad district, Amir Temur",
  "working mode":"Working mode",
  "today":"Today 10:00 - 24:00",
  "waiting today":"We are waiting for you today at 19:00",
  "waiting tomorrow":"We are waiting for you tomorrow at 19:00",

  // Profile page
  "profileCity":"City",
  "personal information":"Personal information",
  "bank card":"Bank card",
  "support chat":"Support Chat",
  "questions and answers":"Questions and answers",
  "exit":"Exit",
  "cancel":"Cancel",
  "ok":"Ok",
  "feedback":"Feedback",
  "telegram":"Telegram",
  "instagram":"Instagram",
  "facebook":"Facebook",
  "choose city":"Choose city",
  "andijan":"Andijan",
  "namangan":"Namangan",
  "fargana":"Fergana",
  "sirdarya":"Syrdarya",
  "jizzax":"Jizzakh",
  "samarkand":"Samarkand",
  "bukhara":"Bukhara",
  "navaiy":"Navaiy",
  "kashkadarya":"Kashkadarya",
  "kharazim":"Kharazim",
  "sukhandarya":"Sukhandarya",

};

