// Russian Translations
const Map<String, String> ruRU = {
  //other project
  'enter_mobile': 'Введите номер \nмобильного телефона',
  'sent_code': 'Мы отправим вам код подтверждения',
  'enter_phone_number': 'Введите номер телефона.',
  'phone_invalid':
      "Ошибка формата номера телефона. Номер телефона должен начинаться с + и состоять из 9-15 цифр.",
  'enter_sms_code': "Введите код, \nотправленный на ваш номер",
  'we_sent_sms': "Отправили на номер ",
  'receive_code': "Я не получил код. ",
  'resend_code': "Отправить код еще раз",
  'next': "Далее",
  'password': "Пароль",
  'new_password': "Новый Пароль",
  'enter_new_password': "Введите новый пароль",
  'confirm_password': "Подтвердите пароль",
  'enter_confirm_password': "Пожалуйста, введите пароль для подтверждения",
  'save': "Сохранять",
  'msg_enter_password': "Parol raqamini kiriting.",
  'msg_enter_confirm_password': "Пожалуйста, введите тот же пароль!",
  'login': "Логин",
  'username': "Имя пользователя",
  'lang': "ru_RU",
  'internal_server_error': "Системная ошибка! Пожалуйста, попробуйте позже!",
  'location': "Место нахождения",
  'clock_in': 'Часы в',
  'clock_out': 'Часы из',
  'working_hr': 'Рабочее время',
  'language': "Язык",
  'log_out': "Выйти",
  'attendance': "Посещаемость",
  'date': "Sana",
  'try_again': "Пожалуйста, попробуйте еще раз!",
  'forget_pressed_button':
      "Вы вчера не нажали кнопку 'Часы из', сообщите об этом начальнику отдела кадров!",
  'disable':
      "Эта кнопка нажимается только тогда, когда вы приходите и уходите!",
  'check_network':
      "Ты не в сети. Пожалуйста, проверьте подключение к интернету!",
  'incorrectly_phone': "Пожалуйста, введите номер, доступный в системе!",
  'invalid_password': "Пожалуйста, введите пароль правильно!",

  // current project
  'intro_header_one': "Боле 2 00 занятий \n с акциями и бонусами",
  'intro_content_one': "Получайте подарки, скидки и боеусны",
  'button_next': "далее",
  "button_enter": "начат",

  //language page
  "str_choose_lang": "Выберите язык",

  //setting_detail_page
  "str_guests": "Гости",
  "str_people_count": "Число людей",
  "str_choose_date": "Выберите дату",
  "str_choose_room": "Выберите комнату",
  "str_choose_time": "Выберите время прибытия",
  "str_clear": "Очистить",
  "str_next": "Дальше",
  "str_room": "Комнота",
  "str_price": "Цена",
  "registration": "Регестрация",
  "full_name": "Ваше полное имя",
  "phone_number": "Номер телефона",
  "using_application": "Используя приложение, вы принимаете условия в \n ",
  "agreements": "соглашения",
  "information_messages": " и соглашаетесь получать рекламные \n и информационные сообщения",

  // Notification page
  "news":"Новости",
  "message":"Сообщении",
  "vastok":"Васток",
  "tashkent":"Ташкент",
  "yunusabad":"Юнусабадский район, Амир Темур",
  "working mode":"Режим роботы",
  "today":"Сегодгя 10:00 - 24:00",
  "waiting today":"Ждем вас сегодгя в 19:00",
  "waiting tomorrow":"Ждем вас завтра в 19:00",

  // Profile page
  "profileCity":"Город",
  "personal information":"Личная информация",
  "bank card":"Банковская карта",
  "support chat":"Чат с поддержкой",
  "questions and answers":"Вопросы и ответы",
  "exit":"Выйти",
  "cancel":"Да",
  "ok":"нет",
  "feedback":"Обратная сквязь",
  "telegram":"Телеграм",
  "instagram":"Инстаграм",
  "facebook":"Фейсбук",
  "choose city":"Выберите город",
  "andijan":"Андижан",
  "namangan":"Наманган",
  "fargana":"Фаргана",
  "sirdarya":"Сирдаря",
  "jizzax":"Жиззах",
  "samarkand":"Самарканд",
  "bukhara":"Букхара",
  "navaiy":"Наваий",
  "kashkadarya":"Кашкадаря",
  "kharazim":"Харазим",
  "sukhandarya":"Сукхандаря",
};
