// Uzbek Translations
const Map<String, String> uzUZ = {
  //other project
  'enter_mobile': 'Mobil telefon \nraqamingizni kiriting',
  'sent_code': 'Biz sizga tasdiqlash kodini yuboramiz',
  'enter_phone_number': 'Telefon raqamingizni kiriting.',
  'phone_invalid': "Telefon raqam formati xato. Telefon raqam + bilan boshlanib, 9 tadan 15 tagacha sonlarda iborat bo'lishi kerak",
  'enter_sms_code': "Raqamingizga yuborilgan \nkodni kiriting",
  'we_sent_sms': "Raqamga yuborildi ",
  'receive_code': "Men kodni olmadim. ",
  'resend_code': "Kodni qayta yuboring",
  'next': "Keyingi",
  'password': "Parol",
  'new_password': "Yangi Parol",
  'enter_new_password': "Yangi parolni kiriting",
  'confirm_password': "Parolni tasdiqlang",
  'enter_confirm_password': "Iltimos, tasdiqlash parolini kiriting",
  'save': "Saqlash",
  'msg_enter_password': "Parolni kiriting.",
  'msg_enter_confirm_password': "Iltimos, xuddi shu parolni kiriting!",
  'login': "Login",
  'username': "Foydalanuvchi nomi",
  'lang': "uz_UZ",
  'internal_server_error':
      "Tizimda xatolik! Iltimos birozdan so'ng qayta urunib ko'ring!",
  'location': "Manzil",
  'clock_in': 'Kirish soati',
  'clock_out': "Soatni o'chirish",
  'working_hr': 'Ish soati',
  'language': "Til",
  'log_out': "Chiqish",
  'attendance': "Davomat",
  'date': "Sana",
  'try_again': "Iltimos, yana bir bor urinib ko'ring!",
  'forget_pressed_button':
      "Siz kecha 'Soatni o'chirish' tugmasini bosmadingiz, iltimos bu haqida hodimlar bo'limi nazoratichisiga xabar bering!",
  'disable': "Bu tugma faqat ishga kelganda va ketganda bosiladi!",
  'check_network': "Siz oflaynsiz. Iltimos, internet aloqangizni tekshiring!",
  'incorrectly_phone': "Iltimos tizimda mavjud bo'lgan raqam kiriting!",
  'invalid_password': "Iltimos parolni to'g'ri kiriting!",

  // current project
  'intro_header_one': "Aktsiyalar va bonuslar  bilan \n 200 dan ortiq sinflar",
  'intro_content_one': "Sovg'alar, chegirmalar va janglarni oling",
  'button_next': "Keyingisi",
  "button_enter": "Kirish",

  //language page
  "str_choose_lang": "Tilni tanlang",

//setting_detail_page
  "str_guests": "Tashrif buyurchilar soni",
  "str_people_count": "Odamlar soni",
  "str_choose_date": "Sanani tanlang",
  "str_choose_room": "Xonani tanlang",
  "str_choose_time": "Kelish vaqtini tanlang",
  "str_clear": "Tozalash",
  "str_next": "Keyingisi",
  "str_room": "Xona",
  "str_price": "Narxi",

  // Notification page
  "news":"Yangiliklar",
  "message":"Xabarlar",
  "vastok":"Vastok",
  "tashkent":"Toshkent",
  "yunusabad":"Yunusobod tumani, Amir Temur",
  "working mode":"Ish tartibi",
  "today":"Bugun 10:00 - 24:00",
  "waiting today":"Bugun sizni kutamiz 19:00 da",
  "waiting tomorrow":"Ertaga sizni kutamiz 19:00 da",

  // Profile page
  "profileCity":"Shahar",
  "personal information":"Shaxsiy ma'lumot",
  "bank card":"Bank kartasi",
  "support chat":"Yordam uchun chat",
  "questions and answers":"Savol va javoblar",
  "exit":"Chiqish",
  "cancel":"Ha",
  "ok":"yo'q",
  "feedback":"Aloqaga chiqish",
  "telegram":"Telegram",
  "instagram":"Instagram",
  "facebook":"Facebook",
  "choose city":"Shaharni tanlang",
  "andijan":"Andijon",
  "namangan":"Namangan",
  "fargana":"Farg'ona",
  "sirdarya":"Sirdaryo",
  "jizzax":"Jizzax",
  "samarkand":"Samarqand",
  "bukhara":"Buxoro",
  "navaiy":"Navoiy",
  "kashkadarya":"Qashqadaryo",
  "kharazim":"Xorazm",
  "sukhandarya":"Surxondaryo",

};